version: "3.8"
services:
  roon-cambridge-audio:
    build: ./
    container_name: roon-cambridge-audio
    restart: unless-stopped
    stdin_open: true
    tty: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
